In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

# Some Universal functions(element wise operation)
### 1. np.sqrt(arr)
### 2. np.exp(arr)
### 3. np.random.randn(number of elements)
### 4.np.maximum(arr1,arr2)                                          computes the element-wise maximum of the elements in arr1 and arr2.
### 5. rem, whole_num = np.modf(arr)


In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

*********************

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

*********************

In [7]:
x1=np.array([1,2,3,4,5])

In [8]:
x2=np.array([2,1,1,5,4])

In [9]:
x1

array([1, 2, 3, 4, 5])

In [10]:
x2

array([2, 1, 1, 5, 4])

In [11]:
np.maximum(x1,x2)

array([2, 2, 3, 5, 5])

In [17]:
np.add(x1,x2)

array([3, 3, 4, 9, 9])

*********************

In [12]:
float_arr = np.array([1.1111, 2.2222, 3.3333, 4.4444, 5.5555])

In [14]:
remainder, whole_number = np.modf(float_arr)

In [15]:
remainder

array([ 0.1111,  0.2222,  0.3333,  0.4444,  0.5555])

In [16]:
whole_number

array([ 1.,  2.,  3.,  4.,  5.])

*********************