In [1]:
import numpy as np

In [2]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [3]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [4]:
arr+arr

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [5]:
arr-arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [7]:
arr/arr

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [8]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [10]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

In [23]:
ar=np.arange(10)

In [24]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Slicing
ar[5:8]

array([5, 6, 7])

In [26]:
ar[5:8]=100

In [27]:
ar

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

### Slicing is reflected in the original array - no copy is created

In [29]:
myarr=np.arange(15)

In [30]:
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
myarr[5:8]

array([5, 6, 7])

In [33]:
myarr_slice = myarr[5:8]

In [36]:
myarr_slice[:] = 99

In [37]:
myarr_slice

array([99, 99, 99])

In [38]:
myarr

array([ 0,  1,  2,  3,  4, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14])

### use myarr[5:8].copy() to copy

In [40]:
myarr_slice1 = myarr[5:8].copy()

In [41]:
myarr_slice1

array([99, 99, 99])

In [42]:
myarr_slice1[:]=100

In [43]:
myarr_slice1

array([100, 100, 100])

In [44]:
myarr

array([ 0,  1,  2,  3,  4, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14])

### Higher Dimensional Array

In [46]:
arr_2d = np.array([[1,2,3],[4,5,6]])

In [47]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr_3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]])

In [49]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr_3d[0][0]

array([1, 2, 3])

In [52]:
arr_3d[0][0][0]

1

In [53]:
arr_3d[1,0]

array([7, 8, 9])

In [54]:
arr_3d[0,0]

array([1, 2, 3])

In [55]:
arr_3d[0,0,0]

1

### Slicing With indexing

In [57]:
a_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [58]:
a_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arr[:2] => select the first 2 rows of (axis 0)

In [61]:
a_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
# Grap till row 2 and column 1 onwards
a_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [66]:
# First row(1th) and column upto 2(0th and 1th)
a_2d[1, :2]

array([4, 5])

In [68]:
# Rows upto 2 and 2th column
a_2d[:2, 2]

array([3, 6])

In [69]:
a_2d[:, :1]

array([[1],
       [4],
       [7]])

### Boolean indexing

In [70]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [71]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='|S4')

In [72]:
names=='Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [73]:
data = np.random.randn(7, 4)

In [74]:
data

array([[-1.20773725,  0.92412146,  0.57570101,  0.37344568],
       [-0.42635491, -0.58032479,  1.31784391, -0.77974412],
       [ 0.34575154,  1.66710219, -2.13213422,  0.57912533],
       [-0.27974399, -0.2218811 , -1.31770086,  0.10658092],
       [-0.58662493, -0.58894213, -0.43459828, -1.18793446],
       [ 1.82033053,  0.86154425, -1.74281305,  0.28065907],
       [-0.04351113,  0.61785521, -0.37223611, -1.52440964]])

In [75]:
data[names=='Bob']

array([[-1.20773725,  0.92412146,  0.57570101,  0.37344568],
       [-0.27974399, -0.2218811 , -1.31770086,  0.10658092]])

In [76]:
data[names == 'Bob', 2:]

array([[ 0.57570101,  0.37344568],
       [-1.31770086,  0.10658092]])

In [77]:
data[names == 'Bob', 3]

array([ 0.37344568,  0.10658092])

### Fancy indexing

In [80]:
same_row = np.array([[0,0],[1,1], [2,2], [3,3], [4,4], [5,5]])

In [81]:
same_row

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [83]:
same_row[[5,1,4]]

array([[5, 5],
       [1, 1],
       [4, 4]])

In [84]:
same_row[[-1, -3, -6]]

array([[5, 5],
       [3, 3],
       [0, 0]])

In [85]:
arr = np.arange(32).reshape((8, 4))

In [86]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [87]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

### Transpose

In [90]:
A = np.array([[1,2], [3,4], [5,6], [7,8]])

In [91]:
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [92]:
A.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [93]:
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Matrix dot product

In [94]:
np.dot(A, A.T)

array([[  5,  11,  17,  23],
       [ 11,  25,  39,  53],
       [ 17,  39,  61,  83],
       [ 23,  53,  83, 113]])

### Higher dimension Transpose

In [95]:
arr = np.arange(16).reshape((2, 2, 4))

In [96]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [97]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [98]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [99]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])