In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

# Some Universal functions(element wise operation)

## Unary Functions

    Function                                            Description
    
    1. abs, fabs                                Compute the absolute value element-wise for integer, floating-point, or complex values
     
    2. sqrt                                     Compute the square root of each element (equivalent to arr ** 0.5)
     
    3. square                                   Compute the square of each element (equivalent to arr ** 2)
     
    4. exp                                      Compute the exponent ex of each element
     
    5. log, log10,log2, log1p                   Natural logarithm (base e), log base 10, log base 2, and log(1+x),                                                  respectively sign Compute the sign of each element: 1 (positive),                                                  0(zero), or –1 (negative) ceil Compute the ceiling of each element                                                  (i.e., the smallest integer greater than or equal to thatnumber)
     
    6. floor                                    Compute the floor of each element (i.e., the largest integer less                                                  than or equal to each element)
     
    7. rint                                     Round elements to the nearest integer, preserving the dtype
     
    8. modf                                     Return fractional and integral parts of array as a separate array
     
    9. isnan                                    Return boolean array indicating whether each value is NaN (Not a                                                    Number)
    10. isfinite, isinf                         Return boolean array indicating whether each element is finite                                                      (non-inf, non-NaN) or infinite, respectively
     
    11. cos, cosh, sin,sinh, tan, tanh          Regular and hyperbolic trigonometric functions
     
    12. arccos, arccosh, arcsin, arcsinh, arctan, arctanh        Inverse trigonometric functions
     
    13. logical_not                               Compute truth value of not x element-wise (equivalent to ~arr).

## Returns multiple array
###  rem, whole_num = np.modf(arr)

## Binary Functions


    add                           Add corresponding elements in arrays
    
    subtract                      Subtract elements in second array from first array
    
    multiply                      Multiply array elements
    
    divide, floor_divide          Divide or floor divide (truncating the remainder)
    
    power                         Raise elements in first array to powers indicated in second array
    
    maximum, fmax                 Element-wise maximum; fmax ignores NaN
    
    minimum, fmin                 Element-wise minimum; fmin ignores NaN
    
    mod                           Element-wise modulus (remainder of division)
    
    copysign                      Copy sign of values in second argument to values in first argument
    
    greater, greater_equal,
    less, less_equal,
    equal, not_equal
                                  Perform element-wise comparison, yielding boolean array (equivalent 
                                  to infix operators >, >=, <, <=, ==, !=)
                                  
    logical_and,
    logical_or, logical_xor
                                  Compute element-wise truth value of logical operation (equivalent to
                                  infix operators & |, ^)


In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.abs(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [11]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

*********************

In [7]:
x1=np.array([1,2,3,4,5])

In [8]:
x2=np.array([2,1,1,5,4])

In [9]:
x1

array([1, 2, 3, 4, 5])

In [10]:
x2

array([2, 1, 1, 5, 4])

In [11]:
np.maximum(x1,x2)

array([2, 2, 3, 5, 5])

In [17]:
np.add(x1,x2)

array([3, 3, 4, 9, 9])

*********************

In [12]:
float_arr = np.array([1.1111, 2.2222, 3.3333, 4.4444, 5.5555])

In [14]:
remainder, whole_number = np.modf(float_arr)

In [15]:
remainder

array([ 0.1111,  0.2222,  0.3333,  0.4444,  0.5555])

In [16]:
whole_number

array([ 1.,  2.,  3.,  4.,  5.])

*********************