### File Input and output with arrays
    1. np.save('filename', arrayname)
    
    2. np.load('filename')
    
    3. np.savez('arr_multiple', a=A, b=B)

In [3]:
import numpy as np

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Saves the array in the file rand_arr_10.npy
np.save('rand_arr_10', arr)

In [8]:
# To load the saved file
np.load('rand_arr_10.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
A = np.arange(0, 10, 2)

In [10]:
B = np.arange(1, 10, 2)

In [11]:
A

array([0, 2, 4, 6, 8])

In [12]:
B

array([1, 3, 5, 7, 9])

In [13]:
# To save multiple files
np.savez('arr_multiple', a=A, b=B)

In [15]:
load_multiple = np.load('arr_multiple.npz')

In [17]:
load_multiple['a']

array([0, 2, 4, 6, 8])

In [18]:
load_multiple['b']

array([1, 3, 5, 7, 9])

In [19]:
load_multiple

In [20]:
# If data compresses well
np.savez_compressed('arrays_compressed.npz', a=A, b=B)